# Generated by Django 5.0.1 on 2024-01-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_email_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11)),
                ('code', models.SmallIntegerField()),
                ('expiration_code', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
