# Generated by Django 5.0.1 on 2024-01-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_discountcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='discount_name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
