# Generated by Django 5.0.1 on 2024-01-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_informations_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='color',
            field=models.ManyToManyField(related_name='products_image', to='products.color'),
        ),
    ]
