# Generated by Django 5.0.1 on 2024-01-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_category_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='products.category'),
        ),
    ]
